name: Run News Bot

on:
  workflow_dispatch:
  schedule:
    - cron: "1 0-23/6 * * *"

jobs:
  run-news-bot:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Download previous posted URLs file
        uses: actions/download-artifact@v3
        with:
          name: posted-urls-file
          path: ./
        continue-on-error: true

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run news bot
        run: timeout 357m python news_bot.py

      - name: Upload posted URLs file as artifact
        if: success()
        uses: actions/upload-artifact@v3
        with:
          name: posted-urls-file
          path: posted_urls.txt
