name: Crypto Price Update Bot

on:
  schedule:
    - cron: "0 */3 * * *"  # Run every 3 hours
  workflow_dispatch:  # Allow manual triggers

jobs:
  run-price-update-bot:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install aiohttp python-telegram-bot

      - name: Run price update bot
        run: python price_update_bot.py

